openapi: 3.0.3
info:
  title: Account Receivable Commitments & Online Contributions
  version: 1.0.0
  description: |
    Endpoints para gestionar compromisos de contribuciones de miembros y declarar pagos digitales
    que luego se procesan como contribuciones en línea y, tras su aprobación, aplican el pago
    a la cuenta por cobrar correspondiente.
servers:
  - url: http://localhost:5200
    description: Desarrollo local
security:
  - bearerAuth: [ ]
paths:
  /api/v1/me/contribution:
    post:
      summary: Registra una contribución en línea del miembro autenticado
      description: El miembro envía el comprobante (opcional) y la solicitud queda pendiente de verificación.
      tags: [ Member Contributions ]
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - amount
                - availabilityAccountId
                - contributionType
                - paidAt
              properties:
                amount:
                  type: number
                  format: float
                  example: 120.5
                availabilityAccountId:
                  type: string
                  description: Cuenta de disponibilidad donde se registrará el ingreso.
                contributionType:
                  type: string
                  enum: [ TITHE, OFFERING ]
                  description: |
                    - `TITHE`: el backend busca automáticamente el concepto "Dízimos de Membros" para la iglesia.
                    - `OFFERING`: requiere `financialConceptId`.
                financialConceptId:
                  type: string
                  description: Requerido cuando contributionType = `OFFERING`.
                paidAt:
                  type: string
                  format: date-time
                  description: Fecha/hora en que se realizó el pago.
                observation:
                  type: string
                  description: Nota opcional del miembro.
                file:
                  type: string
                  format: binary
                  description: Comprobante de transferencia bancaria (opcional).
      responses:
        "201":
          description: Contribución registrada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successful contribution registration
        "400":
          description: Error de dominio (por ejemplo, cuenta de disponibilidad no encontrada).
        "403":
          description: Permiso faltante (`financial_records:add_contributions` o `financial_records:adm_contributions`).
        "422":
          description: Validación fallida.
    get:
      summary: Lista contribuciones en línea declaradas por el miembro autenticado
      tags: [ Member Contributions ]
      security:
        - bearerAuth: [ ]
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [ PENDING_VERIFICATION, PROCESSED, REJECTED ]
          description: Filtra por estado de verificación.
        - in: query
          name: financialConceptId
          schema:
            type: string
          description: Filtra por concepto financiero aplicado.
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
          description: Fecha inicial (inclusive) para filtrar por creación.
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
          description: Fecha final (inclusive) para filtrar por creación.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
        - in: query
          name: perPage
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Lista paginada de contribuciones del miembro.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MemberContributionList"
        "403":
          description: Permiso faltante (`financial_records:list_contributions` o `financial_records:adm_contributions`).
  /api/v1/account-receivable/member/commitments:
    get:
      summary: Lista compromisos de contribución del miembro
      tags: [ Accounts Receivable ]
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [ PENDING, PAID, PENDING_ACCEPTANCE, DENIED ]
          description: Filtra por estado de la cuenta por cobrar.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: perPage
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        "200":
          description: Lista paginada de cuentas por cobrar del miembro.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nextPag:
                    type: integer
                  count:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/AccountReceivable"
        "403":
          description: Permiso faltante (`accounts_receivable:member_commitments` o `accounts_receivable:read`).
  /api/v1/account-receivable/member/payment-declaration:
    post:
      summary: Declara un pago digital de una cuota de compromiso (crea OnlineContribution)
      tags: [ Accounts Receivable ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                accountReceivableId:
                  type: string
                installmentId:
                  type: string
                memberId:
                  type: string
                  description: Se usa para validar que el miembro corresponde al compromiso.
                availabilityAccountId:
                  type: string
                amount:
                  type: number
                  format: float
                voucher:
                  type: string
                  format: binary
                  description: Comprobante de transferencia bancaria (opcional).
              required:
                - accountReceivableId
                - installmentId
                - availabilityAccountId
                - amount
      responses:
        "200":
          description: Contribución registrada en estado pendiente de verificación y la cuota queda marcada como IN_REVIEW.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "422":
          description: Validación fallida.
      security:
        - bearerAuth: [ ]
  /api/v1/finance/contribution/{contributionId}/status/{status}:
    patch:
      summary: Actualiza el estado de una contribución en línea
      tags: [ Financial ]
      parameters:
        - in: path
          name: contributionId
          required: true
          schema:
            type: string
        - in: path
          name: status
          required: true
          schema:
            type: string
            enum:
              - PENDING_VERIFICATION
              - PROCESSED
              - REJECTED
      responses:
        "200":
          description: Contribución actualizada. Si posee referencia a AccountReceivable y queda PROCESSED, se ejecuta el pago de la cuota.
        "404":
          description: Contribución no encontrada.
      security:
        - bearerAuth: [ ]
  /api/v1/account-receivable/pay:
    post:
      summary: Aplica un pago a una o varias cuotas de cuenta por cobrar
      tags: [ Accounts Receivable ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountReceivableId:
                  type: string
                installmentId:
                  type: string
                  description: Si se envían varias, separadas por coma (el backend las divide en installmentIds).
                availabilityAccountId:
                  type: string
                amount:
                  type: number
                  format: float
                voucher:
                  type: string
                  description: Identificador o comprobante de transacción bancaria.
              required:
                - accountReceivableId
                - installmentId
                - availabilityAccountId
                - amount
      responses:
        "200":
          description: Pago aplicado y registro financiero generado.
        "404":
          description: Cuenta por cobrar o cuota no encontrada.
        "422":
          description: Validación fallida.
      security:
        - bearerAuth: [ ]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Installment:
      type: object
      properties:
        installmentId:
          type: string
        amount:
          type: number
        amountPaid:
          type: number
          nullable: true
        amountPending:
          type: number
          nullable: true
        dueDate:
          type: string
          format: date-time
        paymentDate:
          type: string
          format: date-time
          nullable: true
        status:
          type: string
          enum: [ PENDING, IN_REVIEW, PAID, PARTIAL_PAYMENT ]
    AccountReceivable:
      type: object
      properties:
        accountReceivableId:
          type: string
        churchId:
          type: string
        description:
          type: string
        amountTotal:
          type: number
        amountPaid:
          type: number
        amountPending:
          type: number
        status:
          type: string
          enum: [ PENDING, PAID, PENDING_ACCEPTANCE, DENIED ]
        installments:
          type: array
          items:
            $ref: "#/components/schemas/Installment"
        debtor:
          type: object
          properties:
            debtorType:
              type: string
              enum: [ MEMBER, GROUP, EXTERNAL ]
            debtorDNI:
              type: string
            name:
              type: string
            phone:
              type: string
            email:
              type: string
            address:
              type: string
    MemberContribution:
      type: object
      properties:
        contributionId:
          type: string
        amount:
          type: number
          format: float
        status:
          type: string
          enum: [ PENDING_VERIFICATION, PROCESSED, REJECTED ]
        createdAt:
          type: string
          format: date-time
        bankTransferReceipt:
          type: string
          description: URL o identificador del comprobante almacenado.
        bankId:
          type: string
          nullable: true
        type:
          type: string
          enum: [ TITHE, OFFERING ]
        availabilityAccount:
          type: object
          properties:
            accountName:
              type: string
            symbol:
              type: string
        member:
          type: object
          properties:
            memberId:
              type: string
            name:
              type: string
            churchId:
              type: string
        financeConcept:
          type: object
          properties:
            financialConceptId:
              type: string
            name:
              type: string
    MemberContributionList:
      type: object
      properties:
        count:
          type: integer
        nextPag:
          type: integer
          nullable: true
        results:
          type: array
          items:
            $ref: "#/components/schemas/MemberContribution"
