openapi: 3.0.1
info:
  title: Church Finance API - DRE Reports
  description: |
    Endpoints para geração de relatórios DRE (Demonstração do Resultado do Exercício).
    O DRE é um relatório contábil que apresenta o resultado das operações da igreja em um período específico.
  version: '1.0'
security:
  - bearerAuth: [ ]
servers:
  - url: http://localhost:5200/api/v1
paths:
  /reports/finance/dre:
    get:
      summary: Gera relatório DRE em formato JSON
      description: |
        Retorna a Demonstração do Resultado do Exercício (DRE) para uma igreja específica.
        O relatório filtra apenas registros financeiros com status CLEARED ou RECONCILED e que afetam o resultado (affectsResult = true).
      tags: [ DRE Reports ]
      security:
        - bearerAuth: [ ]
      parameters:
        - name: churchId
          in: query
          required: true
          description: Identificador único da igreja
          schema:
            type: string
            example: church-001
        - name: year
          in: query
          required: true
          description: Ano de referência do relatório
          schema:
            type: integer
            example: 2024
        - name: month
          in: query
          required: false
          description: Mês de referência (1-12). Se omitido, retorna o ano completo
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 5
      responses:
        '200':
          description: Relatório DRE gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DREResponse'
              example:
                grossRevenue: 3117.05
                netRevenue: 3117.05
                directCosts: 0
                grossProfit: 3117.05
                operationalExpenses: 101.5
                ministryTransfers: 0
                capexInvestments: 0
                operationalResult: 3015.55
                extraordinaryResults: 0
                netResult: 3015.55
        '400':
          description: Parâmetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Não autenticado
        '403':
          description: Sem permissão para acessar relatórios DRE
        '404':
          description: Igreja não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reports/finance/dre/pdf:
    get:
      summary: Gera relatório DRE em formato PDF
      description: |
        Retorna a Demonstração do Resultado do Exercício (DRE) como um arquivo PDF para download.
        O PDF é formatado seguindo o padrão brasileiro de demonstrações contábeis.
      tags: [ DRE Reports ]
      security:
        - bearerAuth: [ ]
      parameters:
        - name: churchId
          in: query
          required: true
          description: Identificador único da igreja
          schema:
            type: string
            example: church-001
        - name: year
          in: query
          required: true
          description: Ano de referência do relatório
          schema:
            type: integer
            example: 2024
        - name: month
          in: query
          required: false
          description: Mês de referência (1-12). Se omitido, retorna o ano completo
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 5
      responses:
        '200':
          description: PDF gerado com sucesso
          content:
            application/pdf:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: Nome do arquivo para download
              schema:
                type: string
                example: 'attachment; filename="dre-2024-5.pdf"'
        '400':
          description: Parâmetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Não autenticado
        '403':
          description: Sem permissão para acessar relatórios DRE
        '404':
          description: Igreja não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reports/finance/dre/trend:
    get:
      summary: Gera comparação de tendências DRE (mês atual vs anterior)
      description: |
        Retorna a comparação de indicadores DRE do mês solicitado com o mês anterior.
        Permite identificar tendências de crescimento/decrescimento nas métricas financeiras.
        Automaticamente calcula o mês anterior, incluindo rollback de ano (Janeiro 2025 → Dezembro 2024).
      tags: [ DRE Reports ]
      security:
        - bearerAuth: [ ]
      parameters:
        - name: churchId
          in: query
          required: true
          description: Identificador único da igreja
          schema:
            type: string
            example: church-001
        - name: year
          in: query
          required: true
          description: Ano de referência do relatório (mês atual)
          schema:
            type: integer
            example: 2025
        - name: month
          in: query
          required: true
          description: Mês de referência (1-12) para comparação
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 11
      responses:
        '200':
          description: Relatório de tendências gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrendResponse'
              example:
                period:
                  year: 2025
                  month: 11
                trend:
                  revenue:
                    current: 4441.10
                    previous: 3643.05
                  opex:
                    current: 1518.55
                    previous: 1829.57
                  transfers:
                    current: 388.00
                    previous: 369.46
                  capex:
                    current: 721.47
                    previous: 721.47
                  netIncome:
                    current: 1167.01
                    previous: 890.55
        '400':
          description: Parâmetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Não autenticado
        '403':
          description: Sem permissão para acessar relatórios DRE
        '404':
          description: Igreja não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    DREResponse:
      type: object
      required:
        - grossRevenue
        - netRevenue
        - directCosts
        - grossProfit
        - operationalExpenses
        - ministryTransfers
        - capexInvestments
        - operationalResult
        - extraordinaryResults
        - netResult
      properties:
        grossRevenue:
          type: number
          format: double
          description: Total gross revenue for the period (categoria REVENUE)
          example: 3117.05
        netRevenue:
          type: number
          format: double
          description: Receita líquida após deduções (espelha a receita bruta neste modelo)
          example: 3117.05
        directCosts:
          type: number
          format: double
          description: Custos diretos/COGS dos serviços prestados (categoria COGS)
          example: 0
        grossProfit:
          type: number
          format: double
          description: Resultado bruto (netRevenue - directCosts)
          example: 3117.05
        operationalExpenses:
          type: number
          format: double
          description: Despesas operacionais e administrativas (categoria OPEX)
          example: 101.5
        ministryTransfers:
          type: number
          format: double
          description: Repasses e contribuições ministeriais (categoria MINISTRY_TRANSFERS)
          example: 0
        capexInvestments:
          type: number
          format: double
          description: Investimentos CAPEX imobilizados (categoria CAPEX)
          example: 0
        operationalResult:
          type: number
          format: double
          description: Resultado operacional (grossProfit - operationalExpenses - ministryTransfers)
          example: 3015.55
        extraordinaryResults:
          type: number
          format: double
          description: Resultados não operacionais/extraordinários (categoria OTHER)
          example: 0
        netResult:
          type: number
          format: double
          description: Resultado líquido do período (operationalResult + extraordinaryResults - capexInvestments)
          example: 3015.55

    TrendResponse:
      type: object
      required:
        - period
        - trend
      properties:
        period:
          type: object
          required:
            - year
            - month
          properties:
            year:
              type: integer
              description: Ano do período atual
              example: 2025
            month:
              type: integer
              description: Mês do período atual (1-12)
              minimum: 1
              maximum: 12
              example: 11
        trend:
          type: object
          required:
            - revenue
            - opex
            - transfers
            - capex
            - netIncome
          properties:
            revenue:
              $ref: '#/components/schemas/TrendValue'
              description: Comparação de receita bruta (mês atual vs anterior)
            opex:
              $ref: '#/components/schemas/TrendValue'
              description: Comparação de despesas operacionais (mês atual vs anterior)
            transfers:
              $ref: '#/components/schemas/TrendValue'
              description: Comparação de transferências ministeriais (mês atual vs anterior)
            capex:
              $ref: '#/components/schemas/TrendValue'
              description: Comparação de investimentos CAPEX (mês atual vs anterior)
            netIncome:
              $ref: '#/components/schemas/TrendValue'
              description: Comparação de resultado líquido (mês atual vs anterior)

    TrendValue:
      type: object
      required:
        - current
        - previous
      properties:
        current:
          type: number
          format: double
          description: Valor do período atual
          example: 4441.10
        previous:
          type: number
          format: double
          description: Valor do período anterior
          example: 3643.05

    Error:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro
          example: Igreja não encontrada
        code:
          type: string
          description: Código do erro
          example: CHURCH_NOT_FOUND
