export enum NotificationsTopic {
  EVENT_NEW = "EVENT_NEW",
  PAYMENT_COMMITMENT_DUE = "PAYMENT_COMMITMENT_DUE",
  CONTRIBUTION_STATUS_CHANGED = "CONTRIBUTION_STATUS_CHANGED",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
}
