export const INTERNAL_TRANSFER_CONCEPT_TAG = "TRANSFER_INTERNAL"
export const INTERNAL_TRANSFER_CONCEPT_NAME = "TRANSFER_INTERNAL"

export const INTERNAL_TRANSFER_REFERENCE_SOURCE = "INTERNAL_TRANSFER_SOURCE"
export const INTERNAL_TRANSFER_REFERENCE_DESTINATION =
  "INTERNAL_TRANSFER_DESTINATION"
