export enum QueueName {
  UpdateCostCenterMasterJob = "UpdateCostCenterMasterJob",
  MovementBankRecordJob = "MovementBankRecordJob",
  CreateFinancialRecordJob = "CreateFinancialRecordJob",
  UpdateFinancialRecordJob = "UpdateFinancialRecordJob",
  UpdateAvailabilityAccountBalanceJob = "UpdateAvailabilityAccountBalanceJob",
  CreateUserForMemberJob = "CreateUserForMemberJob",
  SendMailJob = "SendMailJob",
  TelegramNotificationJob = "TelegramNotificationJob",
  ProcessInventoryFromFileJob = "ProcessInventoryFromFileJob",
  ImportBankStatementJob = "ImportBankStatementJob",
  OnboardingCustomerJob = "OnboardingCustomerJob",
  BootstrapPermissionsJob = "BootstrapPermissionsJob",
  RebuildAvailabilityMasterAccountJob = "RebuildAvailabilityMasterAccountJob",
  RebuildCostCenterMasterJob = "RebuildCostCenterMasterJob",
  DeletePurchasesJob = "DeletePurchasesJob",
  NotifyFCMJob = "NotifyFCMJob",
  IncomeStatementJob = "IncomeStatementJob",
}
